## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_search/WeatherPy_vacation.csv")
vacation_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Upernavik,72.7868,-56.1549,-10.77,95,100,4.38,GL,2022-02-14 18:27:59
1,Jamestown,42.0970,-79.2353,18.01,47,100,14.97,US,2022-02-14 18:28:00
2,Avarua,-21.2078,-159.7750,77.05,88,100,10.36,CK,2022-02-14 18:28:00
3,Rikitea,-23.1203,-134.9692,78.24,68,63,9.71,PF,2022-02-14 18:29:49
4,Erenhot,43.6475,111.9767,-6.25,84,97,6.35,CN,2022-02-14 18:29:50
...,...,...,...,...,...,...,...,...,...
702,Naliya,23.2667,68.8333,66.27,68,0,5.55,IN,2022-02-14 18:52:56
703,Synya,65.3718,58.0387,8.35,92,73,9.51,RU,2022-02-14 18:52:57
704,Hearst,49.6835,-83.6665,5.25,72,100,8.25,CA,2022-02-14 18:48:44
705,Landerneau,48.4525,-4.2525,48.78,79,75,14.97,FR,2022-02-14 18:49:42
706,Ormara,25.2088,64.6357,70.45,73,0,8.59,PK,2022-02-14 18:52:58

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
hotel_df = vacation_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

info_box_template = """<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
</dl>
"""


# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name. 
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [4]:
hotel_df=hotel_df.loc[hotel_df["Hotel Name"]!=""]
hotel_df

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Upernavik,GL,-10.77,72.7868,-56.1549,Gina's Guesthouse - Upernavik
1,Jamestown,US,18.01,42.0970,-79.2353,Hampton Inn & Suites Jamestown
2,Avarua,CK,77.05,-21.2078,-159.7750,Paradise Inn
3,Rikitea,PF,78.24,-23.1203,-134.9692,People ThankYou
4,Erenhot,CN,-6.25,43.6475,111.9767,Erenhot Rurouni Youth Hostel
...,...,...,...,...,...,...
701,Qena,EG,64.51,26.1615,32.7183,"Grand hotel ""Quena"""
702,Naliya,IN,66.27,23.2667,68.8333,jadeja jayendrasinh
704,Hearst,CA,5.25,49.6835,-83.6665,Companion
705,Landerneau,FR,48.78,48.4525,-4.2525,Le Clos Du Pontic
706,Ormara,PK,70.45,25.2088,64.6357,Kenara Colony house for Rent

In [5]:
# 4a. Add a marker layer for each city to the map.
locations = hotel_df[["Lat", "Lng"]]
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig



# 4b. Display the figure

Figure(layout=FigureLayout(height='420px'))

In [7]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = hotel_df.loc[hotel_df["City"] == "Riyadh"]
vacation_end = vacation_start
vacation_stop1 = hotel_df.loc[hotel_df["City"] =="Hit"]
vacation_stop2 = hotel_df.loc[hotel_df["City"] == "Agara"] 
vacation_stop3 = hotel_df.loc[hotel_df["City"] == "Erzin"]

In [8]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start["Lat"].to_numpy()[0],vacation_start["Lng"].to_numpy()[0]
end = start
stop1 = vacation_stop1["Lat"].to_numpy()[0],vacation_stop1["Lng"].to_numpy()[0]
stop2 = vacation_stop2["Lat"].to_numpy()[0],vacation_stop2["Lng"].to_numpy()[0]
stop3 = vacation_stop3["Lat"].to_numpy()[0],vacation_stop3["Lng"].to_numpy()[0]

In [10]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig=gmaps.figure()
dl_layer=gmaps.directions_layer(start,end,waypoints=[stop1,stop2,stop3],travel_mode="DRIVING")
fig.add_layer(dl_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [12]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start,vacation_stop1,vacation_stop2,vacation_stop3],ignore_index=True)
itinerary_df

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Riyadh,SA,59.14,24.6877,46.7219,"InterContinental Riyadh, an IHG Hotel"
1,Hit,IQ,58.87,33.6416,42.8251,ØµØ§Ù„ÙˆÙ† Ø²ÙŠØ±Ùˆ
2,Agara,GE,30.87,42.0376,43.8238,Silk Road Hotel
3,Erzin,TR,50.72,36.9559,36.2000,Artemis Otel

In [17]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [18]:
# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig


# 11b. Display the figure

Figure(layout=FigureLayout(height='420px'))